#!/usr/bin/env python3
"""Build portable SPARQL consistency rules and version overlays from registries.
Run with --spec-dir to refresh legacy registry snapshots from official .tex files.
Normal builds are offline. Generated artifacts are checked in for other validators.
"""
from pathlib import Path
import argparse, hashlib, json, re
from rdflib import Graph, Namespace, Literal, URIRef
from rdflib.namespace import RDF, OWL, RDFS
ROOT=Path(__file__).resolve().parent.parent
V=Namespace('https://w3id.org/vcf-core/vocab#')
PREFIX='PREFIX vcfc: <https://w3id.org/vcf-core/vocab#>\nPREFIX xsd: <http://www.w3.org/2001/XMLSchema#>\n'
HEADER='@prefix sh: <http://www.w3.org/ns/shacl#> .\n@prefix vcfc: <https://w3id.org/vcf-core/vocab#> .\n@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .\n# Generated by scripts/build-shacl-profiles.py; edit the generator.\n\n'
parts=[]
def rule(name,target,message,body,select=None):
    query=PREFIX+(select or 'SELECT $this WHERE {\n'+body+'\n}')
    query=re.sub(r'SELECT (?!\$this)', 'SELECT $this ', query)
    query=re.sub(r'GROUP BY (?!\$this)', 'GROUP BY $this ', query)
    parts.append(f'vcfc:{name} a sh:NodeShape ; sh:targetClass vcfc:{target} ;\n  sh:sparql [ sh:message {Literal(message).n3()} ;\n    sh:select {Literal(query).n3()} ] .\n')
def count(raw,sep):return f'(STRLEN(STR({raw})) - STRLEN(REPLACE(STR({raw}), "{sep}", "")) + 1)'
def clean(s):
    return re.sub(r'\\(?:texttt|textbf|emph|tt)\{([^{}]*)\}',r'\1',s).replace('\\_','_').replace('$','').strip()

def legacy_snapshots(specdir):
    directory=ROOT/'ontology/versions';directory.mkdir(exist_ok=True)
    for version in ['4.1','4.2','4.3','4.4']:
        source=(Path(specdir)/f'VCFv{version}.tex').read_text(); defs={}
        # Tables in 4.3+ give explicit general reserved declarations.
        for kind,label in [('INFO','reserved-info'),('FORMAT','reserved-genotypes')]:
            marker=source.find('\\label{table:'+label+'}')
            if marker!=-1:
                table=source[source.rfind('\\begin{longtable}',0,marker):source.find('\\end{longtable}',marker)]
                for line in table.splitlines():
                    cells=[clean(x) for x in re.sub(r'\\\\\s*$','',line).split('&')]
                    if len(cells)==4 and cells[2] in ('Integer','Float','Flag','Character','String'):defs[kind,cells[0]]=cells[1:3]
        # Normative SV declarations override introductory examples.
        start=source.index('\\section{INFO keys used for structural variants}')
        end=source.find('\\section{Representing variation',start)
        normative=source[start:end if end!=-1 else len(source)]
        pattern=r'##(INFO|FORMAT)=<ID=([^,]+),Number=([^,]+),Type=([^,]+),Description='
        reserved_prose=set(re.findall(r'\\item ([A-Za-z0-9_]+)\s*:', source[:start]))
        for text in ([source[:start]] if version in ('4.1','4.2') else [])+[normative]:
            for kind,key,num,typ in re.findall(pattern,text):
                if text!=normative and key not in reserved_prose:continue
                if key=='ID' or typ not in ('Integer','Float','Flag','Character','String'):continue
                if (kind,key) not in defs or text==normative:defs[kind,key]=[num,typ]
        # Earlier specifications leave some INFO formats to file headers. We do
        # not manufacture a complete registry where no fixed declaration exists.
        data={'version':version,'source':f'https://raw.githubusercontent.com/samtools/hts-specs/master/VCFv{version}.tex','sha256':hashlib.sha256(source.encode()).hexdigest(),'scope':'Explicit reserved table rows and header declarations in the specification; earlier prose-only definitions remain producer-declared.','definitions':[{'kind':k,'id':i,'number':n,'type':t} for (k,i),(n,t) in sorted(defs.items())]}
        (directory/f'vcf-{version}-reserved.json').write_text(json.dumps(data,indent=2)+'\n')

def main():
    parser=argparse.ArgumentParser();parser.add_argument('--spec-dir');args=parser.parse_args()
    if args.spec_dir:legacy_snapshots(args.spec_dir)
    # Cross-representation consistency. Raw-only values remain legal; explicitly
    # materialized collections must agree with their original source token.
    rule('HeaderVersionAgreementShape','VCFFile','File and fileformat header versions must agree.','''$this vcfc:fileFormat ?version ; vcfc:hasHeader/vcfc:hasHeaderLine ?line .
?line a vcfc:FileFormatHeaderLine ; vcfc:headerValue ?value . FILTER (?value != ?version)''')
    rule('HeaderDeclarationAgreementShape','StructuredHeaderLine','Header attributes must agree with their parsed declaration properties.','''$this vcfc:hasAttribute ?a . ?a vcfc:attributeKey ?key ; vcfc:attributeValue ?value .
OPTIONAL { $this vcfc:fieldId ?fieldId }
OPTIONAL { $this vcfc:contigId ?contigId }
OPTIONAL { $this vcfc:filterId ?filterId }
OPTIONAL { $this vcfc:altId ?altId }
OPTIONAL { $this vcfc:fieldNumber ?number }
OPTIONAL { $this vcfc:fieldType ?type }
FILTER ((?key="ID" && ((BOUND(?fieldId) && ?value!=?fieldId) || (BOUND(?contigId) && ?value!=?contigId) || (BOUND(?filterId) && ?value!=?filterId) || (BOUND(?altId) && ?value!=?altId))) ||
(?key="Number" && BOUND(?number) && ?value!=?number) ||
(?key="Type" && BOUND(?type) && ?value!=REPLACE(STRAFTER(STR(?type),"#"),"Type$","")))''')
    rule('FixedArityAgreementShape','FieldDefinition','Fixed Number and fieldNumberInteger must agree.','''$this vcfc:fieldNumber ?number ; vcfc:fieldNumberInteger ?integer .
FILTER(!REGEX(?number,"^[0-9]+$") || xsd:integer(?number) != ?integer)''')
    rule('AlleleRawAgreementShape','VCFRecord','REF/ALT components must agree with their raw columns and indices.','''$this vcfc:ref ?ref ; vcfc:alt ?alt .
{ $this vcfc:ref ?ref ; vcfc:hasReferenceAllele ?a . ?a vcfc:alleleValue ?value . FILTER(STR(?value)!=STR(?ref)) }
UNION { $this vcfc:alt ?alt ; vcfc:hasAltAllele ?a . ?a vcfc:alleleIndex ?index ; vcfc:alleleValue ?value .
BIND(REPLACE(STR(?alt),CONCAT("^([^,]*,){",STR(?index-1),"}([^,]*).*$"),"$2") AS ?token)
FILTER(STR(?value)!=?token || STR(?alt)="." || ?index > '''+count('?alt',',')+''') }
UNION { $this vcfc:hasAltAllele ?a,?b . ?a vcfc:alleleIndex ?idx . ?b vcfc:alleleIndex ?idx . FILTER(?a!=?b) }''')
    rule('AlleleCountAgreementShape','VCFRecord','A materialized ALT collection must contain every ALT allele.','''$this vcfc:alt ?raw . FILTER EXISTS { $this vcfc:hasAltAllele ?any }
{ SELECT $this (COUNT(DISTINCT ?a) AS ?n) WHERE { $this vcfc:alt ?raw . OPTIONAL { $this vcfc:hasAltAllele ?a } } GROUP BY $this }
FILTER(?n != IF(STR(?raw)=".",0,'''+count('?raw',',')+'''))''')
    rule('GenotypeCallAgreementShape','Genotype','GT text, ploidy, call indices and called alleles must agree.','''$this vcfc:genotypeString ?raw ; vcfc:ploidy ?ploidy .
BIND(REPLACE(STR(?raw),"^[|/]","") AS ?gt)
{ SELECT $this (COUNT(DISTINCT ?call) AS ?n) WHERE { $this vcfc:genotypeString ?raw . OPTIONAL { $this vcfc:hasAlleleCall ?call } } GROUP BY $this }
FILTER (?ploidy != ?n || ?ploidy != '''+count('?gt','[|/]')+''')''')
    rule('GenotypeAlleleAgreementShape','Genotype','Each parsed GT allele and phase indicator must match its source position.','''$this vcfc:genotypeString ?raw ; vcfc:hasAlleleCall ?call .
?call vcfc:callIndex ?index ; vcfc:isNoCall ?missing .
BIND(REPLACE(STR(?raw),"^[|/]","") AS ?gt)
BIND(REPLACE(?gt,CONCAT("^([^|/]*[|/]){",STR(?index),"}([^|/]*).*$"),"$2") AS ?token)
OPTIONAL { ?call vcfc:calledAllele/vcfc:alleleIndex ?allele }
OPTIONAL { ?call vcfc:phaseIndicator ?phase }
BIND(IF(?index=0,IF(REGEX(STR(?raw),"^[|/]"),SUBSTR(STR(?raw),1,1),IF(CONTAINS(STR(?raw),"/"),"/","|")),REPLACE(?gt,CONCAT("^([^|/]*[|/]){",STR(?index-1),"}[^|/]*([|/]).*$"),"$2")) AS ?expectedPhase)
FILTER (?missing != (?token=".") || (?missing && BOUND(?allele)) || (!?missing && (!BOUND(?allele) || STR(?allele)!=?token)) || (BOUND(?phase) && ?phase!=?expectedPhase) || ?index >= '''+count('?gt','[|/]')+''')''')
    rule('GenotypeIndexUniqueShape','Genotype','GT call indices must be unique.','''$this vcfc:hasAlleleCall ?a,?b . ?a vcfc:callIndex ?i . ?b vcfc:callIndex ?i . FILTER(?a!=?b)''')
    rule('ValueItemRawAgreementShape','FieldValueItem','Value items must agree with raw field tokens and contiguous zero-based indices.','''?field vcfc:hasValueItem $this ; vcfc:fieldValue ?raw .
$this vcfc:valueIndex ?idx ; vcfc:itemValue ?value .
BIND(REPLACE(STR(?raw),CONCAT("^([^,]*,){",STR(?idx),"}([^,]*).*$"),"$2") AS ?token)
FILTER (?idx >= '''+count('?raw',',')+''' || (STR(?value)!=?token && !(isNumeric(?value) && xsd:double(?value)=xsd:double(?token))))''')
    rule('ValueItemCountShape','FieldValueItem','A materialized field list must contain each source item exactly once.','''?field vcfc:hasValueItem $this ; vcfc:fieldValue ?raw .
{ SELECT ?field (COUNT(DISTINCT ?item) AS ?n) (COUNT(DISTINCT ?idx) AS ?indices) WHERE { ?field vcfc:hasValueItem ?item . ?item vcfc:valueIndex ?idx } GROUP BY ?field }
FILTER(?n != ?indices || ?n != IF(STR(?raw)="",0,'''+count('?raw',',')+'''))''')
    floatpattern=r'^[-+]?[0-9]*[.]?[0-9]+([eE][-+]?[0-9]+)?$|^[-+]?(INF|INFINITY|NAN)$'
    for cls in ['InfoFieldValue','FormatFieldValue']:
        rule(cls+'LexicalShape',cls,'Field values must match their declared VCF type.','''$this vcfc:declaredBy/vcfc:fieldType ?type ; vcfc:fieldValue ?raw .
FILTER(STR(?raw)!=".")
FILTER((?type=vcfc:IntegerType && !REGEX(STR(?raw),"^([+-]?[0-9]+|[.])(,([+-]?[0-9]+|[.]))*$")) ||
(?type=vcfc:FloatType && !REGEX(STR(?raw),"^([-+]?[0-9]*[.]?[0-9]+([eE][-+]?[0-9]+)?|[-+]?(INF|INFINITY|NAN)|[.])(,([-+]?[0-9]*[.]?[0-9]+([eE][-+]?[0-9]+)?|[-+]?(INF|INFINITY|NAN)|[.]))*$","i")) ||
(?type=vcfc:CharacterType && !REGEX(STR(?raw),"^([^,]|(%[0-9A-Fa-f]{2})+)(,([^,]|(%[0-9A-Fa-f]{2})+))*$")) || ?type=vcfc:FlagType)''')
        # Count raw lists as well as explicit items; absence of optional items
        # cannot bypass Number checking. G/LG is polynomial through ploidy 8;
        # the companion semantic validator handles arbitrary ploidy.
        genotype='-1'
        for p in range(8,0,-1):
            numerator=' * '.join(f'(?alleleN + {i})' for i in range(p));denominator=1
            for i in range(1,p+1):denominator*=i
            genotype=f'IF(?p={p},({numerator})/{denominator},{genotype})'
        rule(cls+'CardinalityShape',cls,'Field cardinality must agree with Number, alleles and ploidy.','''$this vcfc:declaredBy ?d ; vcfc:fieldValue ?raw . ?d vcfc:fieldNumber ?number .
?record vcfc:hasCall ?c ; vcfc:alt ?alt .
{ ?c vcfc:hasInfoValue $this }
UNION { ?c vcfc:hasSampleCall ?sample . ?sample vcfc:hasFormatValue $this }
BIND(IF(STR(?alt)=".",0,'''+count('?alt',',')+''') AS ?n)
OPTIONAL { ?sample vcfc:hasGenotype/vcfc:ploidy ?ploidy }
OPTIONAL { ?sample vcfc:hasFormatValue ?laa . ?laa vcfc:declaredBy/vcfc:fieldId "LAA" ; vcfc:fieldValue ?local }
BIND(COALESCE(?ploidy,2) AS ?p)
BIND(IF(!BOUND(?local) || STR(?local)="." || STR(?local)="",0,'''+count('?local',',')+''') AS ?l)
BIND(IF(?number="LG",?l+1,?n+1) AS ?alleleN)
BIND(IF(REGEX(?number,"^[0-9]+$"),xsd:integer(?number),IF(?number="A",?n,IF(?number="R",?n+1,IF(?number="P",?p,IF(?number="LA",?l,IF(?number="LR",?l+1,IF(?number IN ("G","LG"),'''+genotype+''',-1))))))) AS ?expected)
BIND(IF(STR(?raw)="",0,'''+count('?raw',',')+''') AS ?actual)
FILTER(STR(?raw)!="." && ?expected>=0 && ?expected!=?actual)''')
    rule('TypedFieldIntegerBoundsShape','FieldValueItem','VCF Integer values must fit the permitted signed 32-bit range.','''?field vcfc:hasValueItem $this ; vcfc:declaredBy/vcfc:fieldType vcfc:IntegerType .
$this vcfc:itemValue ?v . FILTER(STR(?v)!="." && (xsd:integer(?v) < -2147483640 || xsd:integer(?v)>2147483647))''')
    rule('MatrixDimensionShape','FormatValueVector','VCFTextVector must have exactly one position per sample.','''$this vcfc:valueEncoding vcfc:VCFTextVector ; (vcfc:encodedValues) ?raw .
?matrix vcfc:hasFormatValueVector $this ; vcfc:appliesToSampleSet ?set .
{ SELECT ?set (COUNT(DISTINCT ?sample) AS ?n) WHERE { ?set vcfc:hasSample ?sample } GROUP BY ?set }
FILTER('''+count('?raw',r'\t')+''' != ?n)''')
    rule('ComponentIdentifierShape','VCFFile','Individual record identifiers must be unique across records.','''$this vcfc:hasRecord ?a,?b .
?a vcfc:hasIdentifier/vcfc:identifierValue ?id . ?b vcfc:hasIdentifier/vcfc:identifierValue ?id . FILTER(?a!=?b)''')
    rule('IdentifierRawShape','RecordIdentifier','Parsed ID components must agree with their raw ID column.','''?record vcfc:hasIdentifier $this ; vcfc:recordId ?raw . $this vcfc:componentIndex ?i ; vcfc:identifierValue ?v .
BIND(REPLACE(STR(?raw),CONCAT("^([^;]*;){",STR(?i-1),"}([^;]*).*$"),"$2") AS ?expected)
FILTER(STR(?raw)="." || ?v!=?expected || ?i>'''+count('?raw',';')+''')''')
    rule('FilterRawShape','FilterCode','Parsed filter failures must agree with FILTER or FT.','''?parent vcfc:hasFilterCode $this . { ?parent vcfc:filter ?raw } UNION { ?parent vcfc:sampleFilter ?raw }
$this vcfc:componentIndex ?i ; vcfc:filterCodeValue ?v .
BIND(REPLACE(STR(?raw),CONCAT("^([^;]*;){",STR(?i-1),"}([^;]*).*$"),"$2") AS ?expected)
FILTER(STR(?raw) IN (".","PASS") || ?v!=?expected || ?i>'''+count('?raw',';')+''')''')
    rule('LocalMembershipShape','LocalAlleleSet','Local membership order must agree with sample LAA and record-global ALT indices.','''?sample vcfc:hasGenotype/vcfc:hasLocalAlleleSet $this ; vcfc:hasFormatValue ?fv . ?fv vcfc:declaredBy/vcfc:fieldId "LAA" ; vcfc:fieldValue ?raw .
$this vcfc:hasLocalAlleleMembership ?member . ?member vcfc:localIndex ?i ; vcfc:localAllele/vcfc:alleleIndex ?a .
BIND(REPLACE(STR(?raw),CONCAT("^([^,]*,){",STR(?i-1),"}([^,]*).*$"),"$2") AS ?expected)
FILTER(STR(?a)!=?expected || ?i>'''+count('?raw',',')+''')''')
    rule('ReferenceBlockExtentShape','ReferenceBlock','A sample reference block must agree with FORMAT LEN and record POS.','''?sample vcfc:hasReferenceBlock $this ; vcfc:hasFormatValue ?fv . ?fv vcfc:declaredBy/vcfc:fieldId "LEN" ; vcfc:fieldValue ?raw .
?record vcfc:pos ?pos ; vcfc:hasCall/vcfc:hasSampleCall ?sample .
$this vcfc:referenceBlockLength ?length ; vcfc:endPosition ?end . FILTER(?length!=xsd:integer(?raw) || ?end!=?pos+?length-1)''')
    (ROOT/'shacl/vcf-core-consistency.shacl.ttl').write_text(HEADER+'\n'.join(parts))
    # Each overlay is scoped by fileFormat. All overlays may be loaded together.
    modern=Graph().parse(ROOT/'ontology/vcf-core-reserved-keys.ttl')
    for minor in range(1,6):
        parts.clear();version=f'4.{minor}';code=f'VCFv{version}'
        if minor<5:
            snapshot=json.loads((ROOT/f'ontology/versions/vcf-{version}-reserved.json').read_text());definitions=snapshot['definitions']
            g=Graph();g.bind('vcfc',V);g.bind('owl',OWL);g.bind('rdfs',RDFS)
            for d in definitions:
                term=V[f'Reserved{d["kind"].title()}_v4{minor}_{d["id"]}'];g.add((term,RDF.type,OWL.NamedIndividual));g.add((term,RDF.type,V.InfoFieldDefinition if d['kind']=='INFO' else V.FormatFieldDefinition))
                for prop,val in [('fieldId',Literal(d['id'])),('fieldNumber',Literal(d['number'])),('fieldType',V[d['type']+'Type']),('fieldDescription',Literal(f'Reserved {d["kind"]} {d["id"]} declaration in VCF {version}.')),('reservedIn',Literal(code))]:g.add((term,V[prop],val))
            (ROOT/f'ontology/versions/vcf-{version}-reserved.ttl').write_text(g.serialize(format='turtle').rstrip()+'\n')
        else:
            definitions=[]
            for cls,kind in [(V.InfoFieldDefinition,'INFO'),(V.FormatFieldDefinition,'FORMAT')]:
                for s in modern.subjects(RDF.type,cls):
                    if modern.value(s,V.fieldId):definitions.append(dict(kind=kind,id=str(modern.value(s,V.fieldId)),number=str(modern.value(s,V.fieldNumber)),type=str(modern.value(s,V.fieldType)).split('#')[-1].replace('Type','')))
        allowed='[0-9]+|A|G|[.]' if minor==1 else '[0-9]+|A|R|G|[.]'
        fmt=allowed+('|P' if minor==4 else '|P|LA|LR|LG|M' if minor==5 else '')
        rule(f'VCF4{minor}NumberShape','VCFFile',f'{code}: Number codes must be supported by this version and field kind.',f'''$this vcfc:fileFormat "{code}" ; vcfc:hasHeader/vcfc:hasHeaderLine ?d . ?d vcfc:fieldNumber ?number .
{{ ?d a vcfc:INFOHeaderLine . FILTER(!REGEX(?number,"^({allowed})$")) }} UNION {{ ?d a vcfc:FORMATHeaderLine . FILTER(!REGEX(?number,"^({fmt})$")) }}''')
        for kind in ['INFO','FORMAT']:
            checks=['(?id='+Literal(d['id']).n3()+' && (?number!='+Literal(d['number']).n3()+' || ?type!=vcfc:'+d['type']+'Type))' for d in definitions if d['kind']==kind]
            rule(f'VCF4{minor}{kind}ReservedShape','VCFFile',f'{code}: reserved {kind} declarations must match this version.',f'''$this vcfc:fileFormat "{code}" ; vcfc:hasHeader/vcfc:hasHeaderLine ?d .
?d a vcfc:{kind}HeaderLine ; vcfc:fieldId ?id ; vcfc:fieldNumber ?number ; vcfc:fieldType ?type .
FILTER({' || '.join(checks)})''')
        if minor<=3:
            rule(f'VCF4{minor}GTShape','VCFFile',f'{code}: leading GT phase indicators require VCF 4.4 or later.',f'''$this vcfc:fileFormat "{code}" ; vcfc:hasRecord/vcfc:hasCall/vcfc:hasSampleCall/vcfc:hasGenotype ?g .
?g vcfc:genotypeString ?gt . FILTER(REGEX(STR(?gt),"^[|/]"))''')
        for keys,width in [('CIPOS|CIEND'+('|CILEN|CICN' if minor>=4 else ''),2),('MEINFO|METRANS',4)]:
            expected=str(width) if minor<=3 else f'{width} * ?altCount'
            rule(f'VCF4{minor}Tuple{width}Shape','VCFFile',f'{code}: SV tuple cardinality must match the version-specific rule.',f'''$this vcfc:fileFormat "{code}" ; vcfc:hasRecord ?record . ?record vcfc:alt ?alt ; vcfc:hasCall/vcfc:hasInfoValue ?fv .
?fv vcfc:declaredBy/vcfc:fieldId ?id ; vcfc:fieldValue ?raw . FILTER(REGEX(?id,"^({keys})$"))
BIND(IF(STR(?alt)=".",0,{count('?alt',',')}) AS ?altCount)
FILTER(STR(?raw)!="." && {count('?raw',',')} != {expected})''')
            # Once parsed alleles exist, these tuple carriers are a complete
            # materialization contract, including the all-items-removed case.
            rule(f'VCF4{minor}Tuple{width}ItemsShape','VCFFile',f'{code}: parsed SV tuples must contain all value items.',f'''$this vcfc:fileFormat "{code}" ; vcfc:hasRecord ?record . ?record vcfc:hasAltAllele ?allele ; vcfc:hasCall/vcfc:hasInfoValue ?fv .
?fv vcfc:declaredBy/vcfc:fieldId ?id ; vcfc:fieldValue ?raw . FILTER(REGEX(?id,"^({keys})$"))
{{ SELECT ?fv (COUNT(DISTINCT ?item) AS ?n) WHERE {{ ?fv vcfc:fieldValue ?raw . OPTIONAL {{ ?fv vcfc:hasValueItem ?item }} }} GROUP BY ?fv }}
FILTER(?n != {count('?raw',',')})''')
        gate=f'vcfc:VCF4{minor}FileGate a sh:NodeShape ; sh:targetClass vcfc:VCF4{minor}File ; sh:property [ sh:path vcfc:fileFormat ; sh:hasValue "{code}" ; sh:maxCount 1 ] .\n'
        (ROOT/f'shacl/vcf-{version}.shacl.ttl').write_text(HEADER+gate+'\n'.join(parts))
    print('Built consistency rules and five version overlays.')
if __name__=='__main__':main()
